//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volunteer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyTalent
    {
        public int Id { get; set; }
        public int FamilyId { get; set; }
        public int TalentId { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Talent Talent { get; set; }
    }
}
