//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volunteer
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Person
    {
        public Person()
        {
            this.Works = new ObservableCollection<Work>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> DefaultFamilyId { get; set; }
        public string Email { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ObservableCollection<Work> Works { get; set; }
    }
}
