//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volunteer
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TaskTalent
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int TalentId { get; set; }
    
        public virtual Talent Talent { get; set; }
        public virtual Task Task { get; set; }
    }
}
