//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volunteer
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskTalents = new ObservableCollection<TaskTalent>();
            this.Works = new ObservableCollection<Work>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ObservableCollection<TaskTalent> TaskTalents { get; set; }
        public virtual ObservableCollection<Work> Works { get; set; }
    }
}
