//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volunteer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class volunteer_dbEntities : DbContext
    {
        public volunteer_dbEntities()
            : base("name=volunteer_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<FamilyTalent> FamilyTalents { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Talent> Talents { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskTalent> TaskTalents { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
